FROM balenalib/aarch64-debian:buster

WORKDIR /app

RUN install_packages \
      stress \
      python3 python3-matplotlib python3-pip python3-setuptools python3-tk bc

COPY requirements.txt ./
RUN pip3 install -r requirements.txt

COPY *.sh ./
COPY server.py ./

CMD ["bash", "start.sh"]
