FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:stretch

WORKDIR /app

RUN install_packages \
      wget omxplayer stress \
      python3 python3-matplotlib python3-pip python3-setuptools python3-tk

COPY requirements.txt ./
RUN pip3 install -r requirements.txt

COPY *.sh ./
COPY server.py ./

CMD ["bash", "start.sh"]
