# Use Raspberry Pi3 (32-bit) base imageses for the 64-bit ARM devices
FROM balenalib/raspberrypi3-debian:stretch

WORKDIR /app

RUN install_packages \
      wget omxplayer stress-ng \
      python3 python3-matplotlib python3-pip python3-setuptools python3-tk

COPY requirements.txt ./
RUN pip3 install -r requirements.txt

COPY *.sh ./
COPY server.py ./

CMD ["bash", "start.sh"]
