FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:buster

WORKDIR /app2

RUN install_packages python2 unzip python-pip python-pil python-setuptools
# RUN pip install pkg_resources
COPY *.sh ./
COPY DS1054Z_screen_capture.zip ./
RUN unzip DS1054Z_screen_capture.zip
CMD ["./start.sh"]
