FROM balenalib/raspberrypi3-debian-python:3.8.2

WORKDIR /app
ENV UDEV=on

# For system
RUN install_packages build-essential libgpiod2 libusb-dev

# For python packages
RUN pip3 install --upgrade setuptools
RUN pip install RPi.GPIO adafruit-blinka adafruit-circuitpython-dht gpiozero pyusb

COPY *.sh ./
COPY *.py ./

CMD ["./start.sh"]